package dev.gopherglide.ggplugin.ci

/**
 * Bundled `.github/workflows/gg.yml` template — implements the headless run -> snap -> assert ->
 * PR-comment pattern documented at https://gopherglide.dev/snap.
 *
 * Adjust the trigger branch and the "Start the application under test" steps to match your project;
 * everything else works out of the box against the latest gg release.
 */
object CiWorkflowTemplate {
    fun render(configPath: String): String = TEMPLATE.replace("{{CONFIG_PATH}}", configPath)

    private val TEMPLATE = """
        # Generated by the Gopher Glide IDE plugin (https://gopherglide.dev).
        # Captures a "main" snapshot baseline on every push to main, then on each PR runs the same
        # config and asserts the PR's snapshot against that baseline, posting the result as a PR
        # comment. Adjust the trigger branch below if your default branch isn't "main".
        name: Gopher Glide Snapshot Regression

        on:
          push:
            branches: [main]
          pull_request:
            branches: [main]

        permissions:
          contents: read
          pull-requests: write

        env:
          GG_CONFIG: "{{CONFIG_PATH}}"

        jobs:
          baseline:
            if: github.event_name == 'push'
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4

              - name: Install gg
                run: |
                  TAG=$(curl -fsSL https://api.github.com/repos/shyam-s00/gopher-glide/releases/latest | grep -o '"tag_name": *"[^"]*"' | cut -d'"' -f4)
                  curl -fsSL -o gg.tar.gz "https://github.com/shyam-s00/gopher-glide/releases/download/${'$'}{TAG}/gg-${'$'}{TAG}-linux-amd64.tar.gz"
                  tar -xzf gg.tar.gz gg
                  chmod +x gg
                  echo "${'$'}PWD" >> "${'$'}GITHUB_PATH"

              # TODO: start the application under test here (e.g. `docker compose up -d`,
              # `./gradlew bootRun &`, ...) — gg needs it reachable before the next step runs.

              - name: Run baseline load test
                run: gg "${'$'}GG_CONFIG" --snap --snap-tag main --headless

              - name: Keep only the latest "main" snapshot
                run: gg snap prune --tag main --keep-last 1 --yes

              - name: Save snapshot baseline
                uses: actions/cache/save@v4
                with:
                  path: ~/.config/gg/snapshots
                  key: gg-snap-main-${'$'}{{ github.run_id }}

          pr-check:
            if: github.event_name == 'pull_request'
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4

              - name: Install gg
                run: |
                  TAG=$(curl -fsSL https://api.github.com/repos/shyam-s00/gopher-glide/releases/latest | grep -o '"tag_name": *"[^"]*"' | cut -d'"' -f4)
                  curl -fsSL -o gg.tar.gz "https://github.com/shyam-s00/gopher-glide/releases/download/${'$'}{TAG}/gg-${'$'}{TAG}-linux-amd64.tar.gz"
                  tar -xzf gg.tar.gz gg
                  chmod +x gg
                  echo "${'$'}PWD" >> "${'$'}GITHUB_PATH"

              # Primary key is unique per run (always a miss) so this always falls back to the
              # latest entry matching restore-keys — i.e. the most recent "main" baseline.
              - name: Restore latest "main" snapshot baseline
                id: restore-baseline
                uses: actions/cache/restore@v4
                with:
                  path: ~/.config/gg/snapshots
                  key: gg-snap-main-${'$'}{{ github.run_id }}
                  restore-keys: |
                    gg-snap-main-

              # TODO: start the application under test here (same as the baseline job above).

              - name: Run PR load test
                run: gg "${'$'}GG_CONFIG" --snap --snap-tag "pr-${'$'}{{ github.event.pull_request.number }}" --headless

              - name: Assert against baseline
                if: steps.restore-baseline.outputs.cache-hit != ''
                run: |
                  gg snap assert \
                    --baseline main \
                    --current "pr-${'$'}{{ github.event.pull_request.number }}" \
                    --latency-regression 10 \
                    --error-rate-delta 0.05 \
                    --payload-size-delta 50 \
                    --reporter md > report.md || echo "GG_ASSERT_FAILED=1" >> "${'$'}GITHUB_ENV"

              - name: No baseline yet
                if: steps.restore-baseline.outputs.cache-hit == ''
                run: echo "No \"main\" baseline snapshot found yet — merge this PR once to seed one." > report.md

              - name: Comment on PR
                uses: actions/github-script@v7
                with:
                  script: |
                    const fs = require('fs');
                    const body = fs.readFileSync('report.md', 'utf8');
                    const marker = '<!-- gopher-glide-snap-report -->';
                    const comment = `${'$'}{marker}\n## Gopher Glide Snapshot Report\n\n${'$'}{body}`;
                    const { data: comments } = await github.rest.issues.listComments({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.issue.number,
                    });
                    const existing = comments.find(c => c.body.includes(marker));
                    if (existing) {
                      await github.rest.issues.updateComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        comment_id: existing.id,
                        body: comment,
                      });
                    } else {
                      await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: comment,
                      });
                    }

              - name: Fail if a regression was detected
                if: env.GG_ASSERT_FAILED == '1'
                run: exit 1
    """.trimIndent()
}
